name: Build MPG123 library (Linux - AMD64)

on:
  push:
    branches: [ "main", "x/oob/v0.1.x", "x/oob/v0.2.x" ]
  pull_request:
    branches: [ "main", "x/oob/v0.1.x", "x/oob/v0.2.x" ]
    
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Setting up environment
        run: |
          sudo apt build-dep mpg123
      - name: Setting up MPG123 library
        run: |
          curl -o mpg123.tar.bz2 https://www.mpg123.de/download/mpg123-1.33.3.tar.bz2
          tar xvf mpg123.tar.bz2
      - name: MPG123 compilation
        run: |
          cd mpg123-1.33.3 ; ./configure ; make
      - name: MPG123 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "MPG123 library - libmpg123"
          path: mpg123-1.33.3/src/libmpg123/.libs/libmpg123.0.dylib
      - name: MPG123 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "MPG123 library - libout123"
          path: mpg123-1.33.3/src/libout123/.libs/libout123.0.dylib
      - name: MPG123 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "MPG123 library - libout123 output modules"
          path: mpg123-1.33.3/src/libout123/modules/.libs/*.so
