name: Build MPG123 library (Windows - AMD64)

on:
  push:
    branches: [ "main", "x/oob/v0.1.x", "x/oob/v0.2.x" ]
  pull_request:
    branches: [ "main", "x/oob/v0.1.x", "x/oob/v0.2.x" ]
    
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Setting up environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            autoconf
            automake
            libtool
            tar
            bzip2
      - name: Setting up MPG123 library
        shell: msys2 {0}
        run: |
          curl -L -o mpg123.tar.bz2 https://www.mpg123.de/download/mpg123-1.33.3.tar.bz2
          tar xvf mpg123.tar.bz2
      - name: MPG123 compilation
        shell: msys2 {0}
        run: |
          cd mpg123-1.33.3 ; ./configure --prefix=/mingw64 --disable-components --enable-libmpg123 --enable-libout123 --enable-libout123-modules --with-default-audio=win32 CFLAGS="-O2 -D__USE_MINGW_ANSI_STDIO=0" ; make ; make install DESTDIR=$PWD/outlib
          cp /mingw64/bin/libgcc_s_seh-1.dll bin/ || true
          cp /mingw64/bin/libwinpthread-1.dll bin/ || true
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "MPG123 library"
          path: mpg123-1.33.3/outlib
