name: Push to PPA

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Import SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          cat > ~/.ssh/config << EOF
          Host ppa.launchpad.net
            IdentityFile ~/.ssh/private.key
            User eofla
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.APT_SSH_PRIV }}
          SSH_KNOWN_HOSTS: ${{ secrets.APT_KNOWN_HOST_FOR_UBUNTU_PPA }}
       
      - name: Configure Launchpad PPA
        run: |
          cat > ~/.dput.cf << EOF
          [apt-ppa]
          fqdn = ppa.launchpad.net
          method = sftp
          incoming = ~eofla/ubuntu/bassboom/
          login = eofla
          allow_unsigned_uploads = 0
          EOF

      - name: Install required packages
        run: |
          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt autoremove dotnet*
          sudo apt update
          sudo NEEDRESTART_SUSPEND=1 apt install curl locales-all libunwind8-dev libcurl4-openssl-dev dotnet-sdk-8.0 libmpv2 devscripts debhelper-compat dput build-essential
        
      - name: Initialize offline package
        run: |
          make init-offline
          make clean
        
      - name: Make original package
        run: |
          mv debian ..
          mv .github ..
          tar cfv ../bassboom-3_2.0.3.0-1.0.0.0.orig.tar .
          xz ../bassboom-3_2.0.3.0-1.0.0.0.orig.tar
          mv ../debian .

      - name: Build source package
        run: debuild -S -sa
        
      - name: Push to Launchpad
        run: dput apt-ppa ../bassboom-3_*_source.changes
