name: Push to PPA (amend with original source)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Import SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          cat > ~/.ssh/config << EOF
          Host ppa.launchpad.net
            IdentityFile ~/.ssh/private.key
            User eofla
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.APT_SSH_PRIV }}
          SSH_KNOWN_HOSTS: ${{ secrets.APT_KNOWN_HOST_FOR_UBUNTU_PPA }}
       
      - name: Configure Launchpad PPA
        run: |
          cat > ~/.dput.cf << EOF
          [apt-ppa]
          fqdn = ppa.launchpad.net
          method = sftp
          incoming = ~eofla/ubuntu/bassboom/
          login = eofla
          allow_unsigned_uploads = 0
          EOF

      - name: Install required packages
        run: |
          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
          sudo NEEDRESTART_SUSPEND=1 apt install devscripts debhelper-compat dput build-essential equivs
          sudo NEEDRESTART_SUSPEND=1 mk-build-deps -i
          
      - name: Download original source
        run: |
          wget --output-document=../bassboom-2_1.0.2.0-0.2.8.0.orig.tar.xz https://launchpad.net/~eofla/+archive/ubuntu/bassboom/+sourcefiles/bassboom-2/1.0.2.0-0.2.8.0/bassboom-2_1.0.2.0-0.2.8.0.orig.tar.xz
          tar xf ../bassboom-2_1.0.2.0-0.2.8.0.orig.tar.xz .
          mv .github ..

      - name: Build source package
        run: debuild -S
        
      - name: Push to Launchpad
        run: dput apt-ppa ../bassboom-2_*_source.changes
